package org.iscas.tj2.pyt.springboot_mybatis.domain;

public class FuncProjectRelation {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FuncProjectRelation.Id_FuncProjectRelation
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	private Integer idFuncprojectrelation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FuncProjectRelation.Id_Function
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	private Integer idFunction;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FuncProjectRelation.Id_Project
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	private Integer idProject;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FuncProjectRelation
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public FuncProjectRelation(Integer idFuncprojectrelation, Integer idFunction, Integer idProject) {
		this.idFuncprojectrelation = idFuncprojectrelation;
		this.idFunction = idFunction;
		this.idProject = idProject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FuncProjectRelation
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public FuncProjectRelation() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FuncProjectRelation.Id_FuncProjectRelation
	 * @return  the value of FuncProjectRelation.Id_FuncProjectRelation
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public Integer getIdFuncprojectrelation() {
		return idFuncprojectrelation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FuncProjectRelation.Id_FuncProjectRelation
	 * @param idFuncprojectrelation  the value for FuncProjectRelation.Id_FuncProjectRelation
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public void setIdFuncprojectrelation(Integer idFuncprojectrelation) {
		this.idFuncprojectrelation = idFuncprojectrelation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FuncProjectRelation.Id_Function
	 * @return  the value of FuncProjectRelation.Id_Function
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public Integer getIdFunction() {
		return idFunction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FuncProjectRelation.Id_Function
	 * @param idFunction  the value for FuncProjectRelation.Id_Function
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public void setIdFunction(Integer idFunction) {
		this.idFunction = idFunction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FuncProjectRelation.Id_Project
	 * @return  the value of FuncProjectRelation.Id_Project
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public Integer getIdProject() {
		return idProject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FuncProjectRelation.Id_Project
	 * @param idProject  the value for FuncProjectRelation.Id_Project
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public void setIdProject(Integer idProject) {
		this.idProject = idProject;
	}
}