package org.iscas.tj2.pyt.springboot_mybatis.domain;

public class FuncVar {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FuncVar.Id_FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	private Integer idFuncvar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FuncVar.Name_FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	private String nameFuncvar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FuncVar.Id_Function
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	private Integer idFunction;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FuncVar.IsParameter_FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	private String isparameterFuncvar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FuncVar.ParameterNO_FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	private Integer parameternoFuncvar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FuncVar.Id_Type
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	private Integer idType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FuncVar.IsSampleType_FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	private Integer issampletypeFuncvar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FuncVar.SampleValue_FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	private String samplevalueFuncvar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FuncVar.Storage_FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	private Integer storageFuncvar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FuncVar.IsParameterPassValueOrAddress_FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	private Integer isparameterpassvalueoraddressFuncvar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FuncVar.Memo_FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	private String memoFuncvar;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public FuncVar(Integer idFuncvar, String nameFuncvar, Integer idFunction, String isparameterFuncvar,
			Integer parameternoFuncvar, Integer idType, Integer issampletypeFuncvar, String samplevalueFuncvar,
			Integer storageFuncvar, Integer isparameterpassvalueoraddressFuncvar, String memoFuncvar) {
		this.idFuncvar = idFuncvar;
		this.nameFuncvar = nameFuncvar;
		this.idFunction = idFunction;
		this.isparameterFuncvar = isparameterFuncvar;
		this.parameternoFuncvar = parameternoFuncvar;
		this.idType = idType;
		this.issampletypeFuncvar = issampletypeFuncvar;
		this.samplevalueFuncvar = samplevalueFuncvar;
		this.storageFuncvar = storageFuncvar;
		this.isparameterpassvalueoraddressFuncvar = isparameterpassvalueoraddressFuncvar;
		this.memoFuncvar = memoFuncvar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public FuncVar() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FuncVar.Id_FuncVar
	 * @return  the value of FuncVar.Id_FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public Integer getIdFuncvar() {
		return idFuncvar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FuncVar.Id_FuncVar
	 * @param idFuncvar  the value for FuncVar.Id_FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public void setIdFuncvar(Integer idFuncvar) {
		this.idFuncvar = idFuncvar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FuncVar.Name_FuncVar
	 * @return  the value of FuncVar.Name_FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public String getNameFuncvar() {
		return nameFuncvar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FuncVar.Name_FuncVar
	 * @param nameFuncvar  the value for FuncVar.Name_FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public void setNameFuncvar(String nameFuncvar) {
		this.nameFuncvar = nameFuncvar == null ? null : nameFuncvar.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FuncVar.Id_Function
	 * @return  the value of FuncVar.Id_Function
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public Integer getIdFunction() {
		return idFunction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FuncVar.Id_Function
	 * @param idFunction  the value for FuncVar.Id_Function
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public void setIdFunction(Integer idFunction) {
		this.idFunction = idFunction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FuncVar.IsParameter_FuncVar
	 * @return  the value of FuncVar.IsParameter_FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public String getIsparameterFuncvar() {
		return isparameterFuncvar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FuncVar.IsParameter_FuncVar
	 * @param isparameterFuncvar  the value for FuncVar.IsParameter_FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public void setIsparameterFuncvar(String isparameterFuncvar) {
		this.isparameterFuncvar = isparameterFuncvar == null ? null : isparameterFuncvar.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FuncVar.ParameterNO_FuncVar
	 * @return  the value of FuncVar.ParameterNO_FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public Integer getParameternoFuncvar() {
		return parameternoFuncvar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FuncVar.ParameterNO_FuncVar
	 * @param parameternoFuncvar  the value for FuncVar.ParameterNO_FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public void setParameternoFuncvar(Integer parameternoFuncvar) {
		this.parameternoFuncvar = parameternoFuncvar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FuncVar.Id_Type
	 * @return  the value of FuncVar.Id_Type
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public Integer getIdType() {
		return idType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FuncVar.Id_Type
	 * @param idType  the value for FuncVar.Id_Type
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public void setIdType(Integer idType) {
		this.idType = idType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FuncVar.IsSampleType_FuncVar
	 * @return  the value of FuncVar.IsSampleType_FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public Integer getIssampletypeFuncvar() {
		return issampletypeFuncvar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FuncVar.IsSampleType_FuncVar
	 * @param issampletypeFuncvar  the value for FuncVar.IsSampleType_FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public void setIssampletypeFuncvar(Integer issampletypeFuncvar) {
		this.issampletypeFuncvar = issampletypeFuncvar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FuncVar.SampleValue_FuncVar
	 * @return  the value of FuncVar.SampleValue_FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public String getSamplevalueFuncvar() {
		return samplevalueFuncvar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FuncVar.SampleValue_FuncVar
	 * @param samplevalueFuncvar  the value for FuncVar.SampleValue_FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public void setSamplevalueFuncvar(String samplevalueFuncvar) {
		this.samplevalueFuncvar = samplevalueFuncvar == null ? null : samplevalueFuncvar.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FuncVar.Storage_FuncVar
	 * @return  the value of FuncVar.Storage_FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public Integer getStorageFuncvar() {
		return storageFuncvar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FuncVar.Storage_FuncVar
	 * @param storageFuncvar  the value for FuncVar.Storage_FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public void setStorageFuncvar(Integer storageFuncvar) {
		this.storageFuncvar = storageFuncvar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FuncVar.IsParameterPassValueOrAddress_FuncVar
	 * @return  the value of FuncVar.IsParameterPassValueOrAddress_FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public Integer getIsparameterpassvalueoraddressFuncvar() {
		return isparameterpassvalueoraddressFuncvar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FuncVar.IsParameterPassValueOrAddress_FuncVar
	 * @param isparameterpassvalueoraddressFuncvar  the value for FuncVar.IsParameterPassValueOrAddress_FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public void setIsparameterpassvalueoraddressFuncvar(Integer isparameterpassvalueoraddressFuncvar) {
		this.isparameterpassvalueoraddressFuncvar = isparameterpassvalueoraddressFuncvar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FuncVar.Memo_FuncVar
	 * @return  the value of FuncVar.Memo_FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public String getMemoFuncvar() {
		return memoFuncvar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FuncVar.Memo_FuncVar
	 * @param memoFuncvar  the value for FuncVar.Memo_FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public void setMemoFuncvar(String memoFuncvar) {
		this.memoFuncvar = memoFuncvar == null ? null : memoFuncvar.trim();
	}
}