package org.iscas.tj2.pyt.springboot_mybatis.domain;

public class FuncStatement {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FuncStatement.Id_FuncStatement
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private Integer idFuncstatement;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FuncStatement.Id_Function
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private Integer idFunction;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FuncStatement.LineNO_FuncStatement
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private Integer linenoFuncstatement;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FuncStatement.Content_FuncStatement
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private String contentFuncstatement;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FuncStatement.Memo_FuncStatement
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private String memoFuncstatement;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FuncStatement.IfBreak_FuncStatement
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private Integer ifbreakFuncstatement;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column FuncStatement.IfAnnotate_FuncStatement
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private Integer ifannotateFuncstatement;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FuncStatement
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public FuncStatement(Integer idFuncstatement, Integer idFunction, Integer linenoFuncstatement,
			String contentFuncstatement, String memoFuncstatement, Integer ifbreakFuncstatement,
			Integer ifannotateFuncstatement) {
		this.idFuncstatement = idFuncstatement;
		this.idFunction = idFunction;
		this.linenoFuncstatement = linenoFuncstatement;
		this.contentFuncstatement = contentFuncstatement;
		this.memoFuncstatement = memoFuncstatement;
		this.ifbreakFuncstatement = ifbreakFuncstatement;
		this.ifannotateFuncstatement = ifannotateFuncstatement;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FuncStatement
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public FuncStatement() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FuncStatement.Id_FuncStatement
	 * @return  the value of FuncStatement.Id_FuncStatement
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public Integer getIdFuncstatement() {
		return idFuncstatement;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FuncStatement.Id_FuncStatement
	 * @param idFuncstatement  the value for FuncStatement.Id_FuncStatement
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setIdFuncstatement(Integer idFuncstatement) {
		this.idFuncstatement = idFuncstatement;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FuncStatement.Id_Function
	 * @return  the value of FuncStatement.Id_Function
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public Integer getIdFunction() {
		return idFunction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FuncStatement.Id_Function
	 * @param idFunction  the value for FuncStatement.Id_Function
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setIdFunction(Integer idFunction) {
		this.idFunction = idFunction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FuncStatement.LineNO_FuncStatement
	 * @return  the value of FuncStatement.LineNO_FuncStatement
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public Integer getLinenoFuncstatement() {
		return linenoFuncstatement;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FuncStatement.LineNO_FuncStatement
	 * @param linenoFuncstatement  the value for FuncStatement.LineNO_FuncStatement
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setLinenoFuncstatement(Integer linenoFuncstatement) {
		this.linenoFuncstatement = linenoFuncstatement;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FuncStatement.Content_FuncStatement
	 * @return  the value of FuncStatement.Content_FuncStatement
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public String getContentFuncstatement() {
		return contentFuncstatement;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FuncStatement.Content_FuncStatement
	 * @param contentFuncstatement  the value for FuncStatement.Content_FuncStatement
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setContentFuncstatement(String contentFuncstatement) {
		this.contentFuncstatement = contentFuncstatement == null ? null : contentFuncstatement.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FuncStatement.Memo_FuncStatement
	 * @return  the value of FuncStatement.Memo_FuncStatement
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public String getMemoFuncstatement() {
		return memoFuncstatement;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FuncStatement.Memo_FuncStatement
	 * @param memoFuncstatement  the value for FuncStatement.Memo_FuncStatement
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setMemoFuncstatement(String memoFuncstatement) {
		this.memoFuncstatement = memoFuncstatement == null ? null : memoFuncstatement.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FuncStatement.IfBreak_FuncStatement
	 * @return  the value of FuncStatement.IfBreak_FuncStatement
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public Integer getIfbreakFuncstatement() {
		return ifbreakFuncstatement;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FuncStatement.IfBreak_FuncStatement
	 * @param ifbreakFuncstatement  the value for FuncStatement.IfBreak_FuncStatement
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setIfbreakFuncstatement(Integer ifbreakFuncstatement) {
		this.ifbreakFuncstatement = ifbreakFuncstatement;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column FuncStatement.IfAnnotate_FuncStatement
	 * @return  the value of FuncStatement.IfAnnotate_FuncStatement
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public Integer getIfannotateFuncstatement() {
		return ifannotateFuncstatement;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column FuncStatement.IfAnnotate_FuncStatement
	 * @param ifannotateFuncstatement  the value for FuncStatement.IfAnnotate_FuncStatement
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setIfannotateFuncstatement(Integer ifannotateFuncstatement) {
		this.ifannotateFuncstatement = ifannotateFuncstatement;
	}
}