package org.iscas.tj2.pyt.springboot_mybatis.domain;

public class NameSpace {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NameSpace.Id_NameSpace
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	private Integer idNamespace;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column NameSpace.Name_NameSpacecol
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	private String nameNamespacecol;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table NameSpace
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public NameSpace(Integer idNamespace, String nameNamespacecol) {
		this.idNamespace = idNamespace;
		this.nameNamespacecol = nameNamespacecol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table NameSpace
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public NameSpace() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NameSpace.Id_NameSpace
	 * @return  the value of NameSpace.Id_NameSpace
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public Integer getIdNamespace() {
		return idNamespace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NameSpace.Id_NameSpace
	 * @param idNamespace  the value for NameSpace.Id_NameSpace
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public void setIdNamespace(Integer idNamespace) {
		this.idNamespace = idNamespace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column NameSpace.Name_NameSpacecol
	 * @return  the value of NameSpace.Name_NameSpacecol
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public String getNameNamespacecol() {
		return nameNamespacecol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column NameSpace.Name_NameSpacecol
	 * @param nameNamespacecol  the value for NameSpace.Name_NameSpacecol
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public void setNameNamespacecol(String nameNamespacecol) {
		this.nameNamespacecol = nameNamespacecol == null ? null : nameNamespacecol.trim();
	}
}