package org.iscas.tj2.pyt.springboot_mybatis.domain;

public class Permission {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Permission.Id_Permission
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private Integer idPermission;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Permission.Id_Project
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private Integer idProject;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Permission.Right_Permission
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private Integer rightPermission;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Permission
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public Permission(Integer idPermission, Integer idProject, Integer rightPermission) {
		this.idPermission = idPermission;
		this.idProject = idProject;
		this.rightPermission = rightPermission;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Permission
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public Permission() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Permission.Id_Permission
	 * @return  the value of Permission.Id_Permission
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public Integer getIdPermission() {
		return idPermission;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Permission.Id_Permission
	 * @param idPermission  the value for Permission.Id_Permission
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setIdPermission(Integer idPermission) {
		this.idPermission = idPermission;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Permission.Id_Project
	 * @return  the value of Permission.Id_Project
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public Integer getIdProject() {
		return idProject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Permission.Id_Project
	 * @param idProject  the value for Permission.Id_Project
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setIdProject(Integer idProject) {
		this.idProject = idProject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Permission.Right_Permission
	 * @return  the value of Permission.Right_Permission
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public Integer getRightPermission() {
		return rightPermission;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Permission.Right_Permission
	 * @param rightPermission  the value for Permission.Right_Permission
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setRightPermission(Integer rightPermission) {
		this.rightPermission = rightPermission;
	}
}