package org.iscas.tj2.pyt.springboot_mybatis.domain;

public class Role {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Role.Id_Role
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	private Integer idRole;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Role.Name_Role
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	private String nameRole;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Role.Desc_Role
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	private String descRole;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Role.Memo_Role
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	private String memoRole;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Role
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public Role(Integer idRole, String nameRole, String descRole, String memoRole) {
		this.idRole = idRole;
		this.nameRole = nameRole;
		this.descRole = descRole;
		this.memoRole = memoRole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Role
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public Role() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Role.Id_Role
	 * @return  the value of Role.Id_Role
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public Integer getIdRole() {
		return idRole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Role.Id_Role
	 * @param idRole  the value for Role.Id_Role
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public void setIdRole(Integer idRole) {
		this.idRole = idRole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Role.Name_Role
	 * @return  the value of Role.Name_Role
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public String getNameRole() {
		return nameRole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Role.Name_Role
	 * @param nameRole  the value for Role.Name_Role
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public void setNameRole(String nameRole) {
		this.nameRole = nameRole == null ? null : nameRole.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Role.Desc_Role
	 * @return  the value of Role.Desc_Role
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public String getDescRole() {
		return descRole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Role.Desc_Role
	 * @param descRole  the value for Role.Desc_Role
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public void setDescRole(String descRole) {
		this.descRole = descRole == null ? null : descRole.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Role.Memo_Role
	 * @return  the value of Role.Memo_Role
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public String getMemoRole() {
		return memoRole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Role.Memo_Role
	 * @param memoRole  the value for Role.Memo_Role
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	public void setMemoRole(String memoRole) {
		this.memoRole = memoRole == null ? null : memoRole.trim();
	}
}