package org.iscas.tj2.pyt.springboot_mybatis.domain;

public class StructUserRelation {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column StructUserRelation.Id_StructUserRelation
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	private Integer idStructuserrelation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column StructUserRelation.Id_Struct
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	private Integer idStruct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column StructUserRelation.Id_User
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	private Integer idUser;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table StructUserRelation
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public StructUserRelation(Integer idStructuserrelation, Integer idStruct, Integer idUser) {
		this.idStructuserrelation = idStructuserrelation;
		this.idStruct = idStruct;
		this.idUser = idUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table StructUserRelation
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public StructUserRelation() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column StructUserRelation.Id_StructUserRelation
	 * @return  the value of StructUserRelation.Id_StructUserRelation
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public Integer getIdStructuserrelation() {
		return idStructuserrelation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column StructUserRelation.Id_StructUserRelation
	 * @param idStructuserrelation  the value for StructUserRelation.Id_StructUserRelation
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public void setIdStructuserrelation(Integer idStructuserrelation) {
		this.idStructuserrelation = idStructuserrelation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column StructUserRelation.Id_Struct
	 * @return  the value of StructUserRelation.Id_Struct
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public Integer getIdStruct() {
		return idStruct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column StructUserRelation.Id_Struct
	 * @param idStruct  the value for StructUserRelation.Id_Struct
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public void setIdStruct(Integer idStruct) {
		this.idStruct = idStruct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column StructUserRelation.Id_User
	 * @return  the value of StructUserRelation.Id_User
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public Integer getIdUser() {
		return idUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column StructUserRelation.Id_User
	 * @param idUser  the value for StructUserRelation.Id_User
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}
}