package org.iscas.tj2.pyt.springboot_mybatis.domain;

public class StructItem {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column StructItem.Id_StructItem
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	private Integer idStructitem;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column StructItem.NO_StructItem
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	private Integer noStructitem;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column StructItem.Id_Type
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	private Integer idType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column StructItem.Name_StructItem
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	private String nameStructitem;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column StructItem.DefaultValue_StructItem
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	private String defaultvalueStructitem;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column StructItem.Memo_StructItem
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	private String memoStructitem;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column StructItem.Id_NameSpace
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	private Integer idNamespace;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column StructItem.IsSampleType_StructItem
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	private Integer issampletypeStructitem;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table StructItem
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public StructItem(Integer idStructitem, Integer noStructitem, Integer idType, String nameStructitem,
			String defaultvalueStructitem, String memoStructitem, Integer idNamespace, Integer issampletypeStructitem) {
		this.idStructitem = idStructitem;
		this.noStructitem = noStructitem;
		this.idType = idType;
		this.nameStructitem = nameStructitem;
		this.defaultvalueStructitem = defaultvalueStructitem;
		this.memoStructitem = memoStructitem;
		this.idNamespace = idNamespace;
		this.issampletypeStructitem = issampletypeStructitem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table StructItem
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public StructItem() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column StructItem.Id_StructItem
	 * @return  the value of StructItem.Id_StructItem
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public Integer getIdStructitem() {
		return idStructitem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column StructItem.Id_StructItem
	 * @param idStructitem  the value for StructItem.Id_StructItem
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public void setIdStructitem(Integer idStructitem) {
		this.idStructitem = idStructitem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column StructItem.NO_StructItem
	 * @return  the value of StructItem.NO_StructItem
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public Integer getNoStructitem() {
		return noStructitem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column StructItem.NO_StructItem
	 * @param noStructitem  the value for StructItem.NO_StructItem
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public void setNoStructitem(Integer noStructitem) {
		this.noStructitem = noStructitem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column StructItem.Id_Type
	 * @return  the value of StructItem.Id_Type
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public Integer getIdType() {
		return idType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column StructItem.Id_Type
	 * @param idType  the value for StructItem.Id_Type
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public void setIdType(Integer idType) {
		this.idType = idType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column StructItem.Name_StructItem
	 * @return  the value of StructItem.Name_StructItem
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public String getNameStructitem() {
		return nameStructitem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column StructItem.Name_StructItem
	 * @param nameStructitem  the value for StructItem.Name_StructItem
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public void setNameStructitem(String nameStructitem) {
		this.nameStructitem = nameStructitem == null ? null : nameStructitem.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column StructItem.DefaultValue_StructItem
	 * @return  the value of StructItem.DefaultValue_StructItem
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public String getDefaultvalueStructitem() {
		return defaultvalueStructitem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column StructItem.DefaultValue_StructItem
	 * @param defaultvalueStructitem  the value for StructItem.DefaultValue_StructItem
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public void setDefaultvalueStructitem(String defaultvalueStructitem) {
		this.defaultvalueStructitem = defaultvalueStructitem == null ? null : defaultvalueStructitem.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column StructItem.Memo_StructItem
	 * @return  the value of StructItem.Memo_StructItem
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public String getMemoStructitem() {
		return memoStructitem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column StructItem.Memo_StructItem
	 * @param memoStructitem  the value for StructItem.Memo_StructItem
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public void setMemoStructitem(String memoStructitem) {
		this.memoStructitem = memoStructitem == null ? null : memoStructitem.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column StructItem.Id_NameSpace
	 * @return  the value of StructItem.Id_NameSpace
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public Integer getIdNamespace() {
		return idNamespace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column StructItem.Id_NameSpace
	 * @param idNamespace  the value for StructItem.Id_NameSpace
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public void setIdNamespace(Integer idNamespace) {
		this.idNamespace = idNamespace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column StructItem.IsSampleType_StructItem
	 * @return  the value of StructItem.IsSampleType_StructItem
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public Integer getIssampletypeStructitem() {
		return issampletypeStructitem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column StructItem.IsSampleType_StructItem
	 * @param issampletypeStructitem  the value for StructItem.IsSampleType_StructItem
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public void setIssampletypeStructitem(Integer issampletypeStructitem) {
		this.issampletypeStructitem = issampletypeStructitem;
	}
}