package org.iscas.tj2.pyt.springboot_mybatis.domain;

public class Struct {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Struct.Id_Struct
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private Integer idStruct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Struct.Name_Struct
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private String nameStruct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Struct.Memo_Struct
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private String memoStruct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Struct.Id_NameSpace_Struct
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private Integer idNamespaceStruct;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Struct
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public Struct(Integer idStruct, String nameStruct, String memoStruct, Integer idNamespaceStruct) {
		this.idStruct = idStruct;
		this.nameStruct = nameStruct;
		this.memoStruct = memoStruct;
		this.idNamespaceStruct = idNamespaceStruct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Struct
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public Struct() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Struct.Id_Struct
	 * @return  the value of Struct.Id_Struct
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public Integer getIdStruct() {
		return idStruct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Struct.Id_Struct
	 * @param idStruct  the value for Struct.Id_Struct
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setIdStruct(Integer idStruct) {
		this.idStruct = idStruct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Struct.Name_Struct
	 * @return  the value of Struct.Name_Struct
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public String getNameStruct() {
		return nameStruct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Struct.Name_Struct
	 * @param nameStruct  the value for Struct.Name_Struct
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setNameStruct(String nameStruct) {
		this.nameStruct = nameStruct == null ? null : nameStruct.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Struct.Memo_Struct
	 * @return  the value of Struct.Memo_Struct
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public String getMemoStruct() {
		return memoStruct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Struct.Memo_Struct
	 * @param memoStruct  the value for Struct.Memo_Struct
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setMemoStruct(String memoStruct) {
		this.memoStruct = memoStruct == null ? null : memoStruct.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Struct.Id_NameSpace_Struct
	 * @return  the value of Struct.Id_NameSpace_Struct
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public Integer getIdNamespaceStruct() {
		return idNamespaceStruct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Struct.Id_NameSpace_Struct
	 * @param idNamespaceStruct  the value for Struct.Id_NameSpace_Struct
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setIdNamespaceStruct(Integer idNamespaceStruct) {
		this.idNamespaceStruct = idNamespaceStruct;
	}
}