package org.iscas.tj2.pyt.springboot_mybatis.domain;

import java.util.ArrayList;
import java.util.List;

public class UserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table User
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table User
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table User
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public UserExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table User
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andId_UserIsNull() {
			addCriterion("Id_User is null");
			return (Criteria) this;
		}

		public Criteria andId_UserIsNotNull() {
			addCriterion("Id_User is not null");
			return (Criteria) this;
		}

		public Criteria andId_UserEqualTo(Integer value) {
			addCriterion("Id_User =", value, "id_User");
			return (Criteria) this;
		}

		public Criteria andId_UserNotEqualTo(Integer value) {
			addCriterion("Id_User <>", value, "id_User");
			return (Criteria) this;
		}

		public Criteria andId_UserGreaterThan(Integer value) {
			addCriterion("Id_User >", value, "id_User");
			return (Criteria) this;
		}

		public Criteria andId_UserGreaterThanOrEqualTo(Integer value) {
			addCriterion("Id_User >=", value, "id_User");
			return (Criteria) this;
		}

		public Criteria andId_UserLessThan(Integer value) {
			addCriterion("Id_User <", value, "id_User");
			return (Criteria) this;
		}

		public Criteria andId_UserLessThanOrEqualTo(Integer value) {
			addCriterion("Id_User <=", value, "id_User");
			return (Criteria) this;
		}

		public Criteria andId_UserIn(List<Integer> values) {
			addCriterion("Id_User in", values, "id_User");
			return (Criteria) this;
		}

		public Criteria andId_UserNotIn(List<Integer> values) {
			addCriterion("Id_User not in", values, "id_User");
			return (Criteria) this;
		}

		public Criteria andId_UserBetween(Integer value1, Integer value2) {
			addCriterion("Id_User between", value1, value2, "id_User");
			return (Criteria) this;
		}

		public Criteria andId_UserNotBetween(Integer value1, Integer value2) {
			addCriterion("Id_User not between", value1, value2, "id_User");
			return (Criteria) this;
		}

		public Criteria andWeixinId_UserIsNull() {
			addCriterion("WeixinId_User is null");
			return (Criteria) this;
		}

		public Criteria andWeixinId_UserIsNotNull() {
			addCriterion("WeixinId_User is not null");
			return (Criteria) this;
		}

		public Criteria andWeixinId_UserEqualTo(String value) {
			addCriterion("WeixinId_User =", value, "weixinId_User");
			return (Criteria) this;
		}

		public Criteria andWeixinId_UserNotEqualTo(String value) {
			addCriterion("WeixinId_User <>", value, "weixinId_User");
			return (Criteria) this;
		}

		public Criteria andWeixinId_UserGreaterThan(String value) {
			addCriterion("WeixinId_User >", value, "weixinId_User");
			return (Criteria) this;
		}

		public Criteria andWeixinId_UserGreaterThanOrEqualTo(String value) {
			addCriterion("WeixinId_User >=", value, "weixinId_User");
			return (Criteria) this;
		}

		public Criteria andWeixinId_UserLessThan(String value) {
			addCriterion("WeixinId_User <", value, "weixinId_User");
			return (Criteria) this;
		}

		public Criteria andWeixinId_UserLessThanOrEqualTo(String value) {
			addCriterion("WeixinId_User <=", value, "weixinId_User");
			return (Criteria) this;
		}

		public Criteria andWeixinId_UserLike(String value) {
			addCriterion("WeixinId_User like", value, "weixinId_User");
			return (Criteria) this;
		}

		public Criteria andWeixinId_UserNotLike(String value) {
			addCriterion("WeixinId_User not like", value, "weixinId_User");
			return (Criteria) this;
		}

		public Criteria andWeixinId_UserIn(List<String> values) {
			addCriterion("WeixinId_User in", values, "weixinId_User");
			return (Criteria) this;
		}

		public Criteria andWeixinId_UserNotIn(List<String> values) {
			addCriterion("WeixinId_User not in", values, "weixinId_User");
			return (Criteria) this;
		}

		public Criteria andWeixinId_UserBetween(String value1, String value2) {
			addCriterion("WeixinId_User between", value1, value2, "weixinId_User");
			return (Criteria) this;
		}

		public Criteria andWeixinId_UserNotBetween(String value1, String value2) {
			addCriterion("WeixinId_User not between", value1, value2, "weixinId_User");
			return (Criteria) this;
		}

		public Criteria andAccount_UserIsNull() {
			addCriterion("Account_User is null");
			return (Criteria) this;
		}

		public Criteria andAccount_UserIsNotNull() {
			addCriterion("Account_User is not null");
			return (Criteria) this;
		}

		public Criteria andAccount_UserEqualTo(String value) {
			addCriterion("Account_User =", value, "account_User");
			return (Criteria) this;
		}

		public Criteria andAccount_UserNotEqualTo(String value) {
			addCriterion("Account_User <>", value, "account_User");
			return (Criteria) this;
		}

		public Criteria andAccount_UserGreaterThan(String value) {
			addCriterion("Account_User >", value, "account_User");
			return (Criteria) this;
		}

		public Criteria andAccount_UserGreaterThanOrEqualTo(String value) {
			addCriterion("Account_User >=", value, "account_User");
			return (Criteria) this;
		}

		public Criteria andAccount_UserLessThan(String value) {
			addCriterion("Account_User <", value, "account_User");
			return (Criteria) this;
		}

		public Criteria andAccount_UserLessThanOrEqualTo(String value) {
			addCriterion("Account_User <=", value, "account_User");
			return (Criteria) this;
		}

		public Criteria andAccount_UserLike(String value) {
			addCriterion("Account_User like", value, "account_User");
			return (Criteria) this;
		}

		public Criteria andAccount_UserNotLike(String value) {
			addCriterion("Account_User not like", value, "account_User");
			return (Criteria) this;
		}

		public Criteria andAccount_UserIn(List<String> values) {
			addCriterion("Account_User in", values, "account_User");
			return (Criteria) this;
		}

		public Criteria andAccount_UserNotIn(List<String> values) {
			addCriterion("Account_User not in", values, "account_User");
			return (Criteria) this;
		}

		public Criteria andAccount_UserBetween(String value1, String value2) {
			addCriterion("Account_User between", value1, value2, "account_User");
			return (Criteria) this;
		}

		public Criteria andAccount_UserNotBetween(String value1, String value2) {
			addCriterion("Account_User not between", value1, value2, "account_User");
			return (Criteria) this;
		}

		public Criteria andPwd_UserIsNull() {
			addCriterion("Pwd_User is null");
			return (Criteria) this;
		}

		public Criteria andPwd_UserIsNotNull() {
			addCriterion("Pwd_User is not null");
			return (Criteria) this;
		}

		public Criteria andPwd_UserEqualTo(String value) {
			addCriterion("Pwd_User =", value, "pwd_User");
			return (Criteria) this;
		}

		public Criteria andPwd_UserNotEqualTo(String value) {
			addCriterion("Pwd_User <>", value, "pwd_User");
			return (Criteria) this;
		}

		public Criteria andPwd_UserGreaterThan(String value) {
			addCriterion("Pwd_User >", value, "pwd_User");
			return (Criteria) this;
		}

		public Criteria andPwd_UserGreaterThanOrEqualTo(String value) {
			addCriterion("Pwd_User >=", value, "pwd_User");
			return (Criteria) this;
		}

		public Criteria andPwd_UserLessThan(String value) {
			addCriterion("Pwd_User <", value, "pwd_User");
			return (Criteria) this;
		}

		public Criteria andPwd_UserLessThanOrEqualTo(String value) {
			addCriterion("Pwd_User <=", value, "pwd_User");
			return (Criteria) this;
		}

		public Criteria andPwd_UserLike(String value) {
			addCriterion("Pwd_User like", value, "pwd_User");
			return (Criteria) this;
		}

		public Criteria andPwd_UserNotLike(String value) {
			addCriterion("Pwd_User not like", value, "pwd_User");
			return (Criteria) this;
		}

		public Criteria andPwd_UserIn(List<String> values) {
			addCriterion("Pwd_User in", values, "pwd_User");
			return (Criteria) this;
		}

		public Criteria andPwd_UserNotIn(List<String> values) {
			addCriterion("Pwd_User not in", values, "pwd_User");
			return (Criteria) this;
		}

		public Criteria andPwd_UserBetween(String value1, String value2) {
			addCriterion("Pwd_User between", value1, value2, "pwd_User");
			return (Criteria) this;
		}

		public Criteria andPwd_UserNotBetween(String value1, String value2) {
			addCriterion("Pwd_User not between", value1, value2, "pwd_User");
			return (Criteria) this;
		}

		public Criteria andName_UserIsNull() {
			addCriterion("Name_User is null");
			return (Criteria) this;
		}

		public Criteria andName_UserIsNotNull() {
			addCriterion("Name_User is not null");
			return (Criteria) this;
		}

		public Criteria andName_UserEqualTo(String value) {
			addCriterion("Name_User =", value, "name_User");
			return (Criteria) this;
		}

		public Criteria andName_UserNotEqualTo(String value) {
			addCriterion("Name_User <>", value, "name_User");
			return (Criteria) this;
		}

		public Criteria andName_UserGreaterThan(String value) {
			addCriterion("Name_User >", value, "name_User");
			return (Criteria) this;
		}

		public Criteria andName_UserGreaterThanOrEqualTo(String value) {
			addCriterion("Name_User >=", value, "name_User");
			return (Criteria) this;
		}

		public Criteria andName_UserLessThan(String value) {
			addCriterion("Name_User <", value, "name_User");
			return (Criteria) this;
		}

		public Criteria andName_UserLessThanOrEqualTo(String value) {
			addCriterion("Name_User <=", value, "name_User");
			return (Criteria) this;
		}

		public Criteria andName_UserLike(String value) {
			addCriterion("Name_User like", value, "name_User");
			return (Criteria) this;
		}

		public Criteria andName_UserNotLike(String value) {
			addCriterion("Name_User not like", value, "name_User");
			return (Criteria) this;
		}

		public Criteria andName_UserIn(List<String> values) {
			addCriterion("Name_User in", values, "name_User");
			return (Criteria) this;
		}

		public Criteria andName_UserNotIn(List<String> values) {
			addCriterion("Name_User not in", values, "name_User");
			return (Criteria) this;
		}

		public Criteria andName_UserBetween(String value1, String value2) {
			addCriterion("Name_User between", value1, value2, "name_User");
			return (Criteria) this;
		}

		public Criteria andName_UserNotBetween(String value1, String value2) {
			addCriterion("Name_User not between", value1, value2, "name_User");
			return (Criteria) this;
		}

		public Criteria andPhone_UserIsNull() {
			addCriterion("Phone_User is null");
			return (Criteria) this;
		}

		public Criteria andPhone_UserIsNotNull() {
			addCriterion("Phone_User is not null");
			return (Criteria) this;
		}

		public Criteria andPhone_UserEqualTo(String value) {
			addCriterion("Phone_User =", value, "phone_User");
			return (Criteria) this;
		}

		public Criteria andPhone_UserNotEqualTo(String value) {
			addCriterion("Phone_User <>", value, "phone_User");
			return (Criteria) this;
		}

		public Criteria andPhone_UserGreaterThan(String value) {
			addCriterion("Phone_User >", value, "phone_User");
			return (Criteria) this;
		}

		public Criteria andPhone_UserGreaterThanOrEqualTo(String value) {
			addCriterion("Phone_User >=", value, "phone_User");
			return (Criteria) this;
		}

		public Criteria andPhone_UserLessThan(String value) {
			addCriterion("Phone_User <", value, "phone_User");
			return (Criteria) this;
		}

		public Criteria andPhone_UserLessThanOrEqualTo(String value) {
			addCriterion("Phone_User <=", value, "phone_User");
			return (Criteria) this;
		}

		public Criteria andPhone_UserLike(String value) {
			addCriterion("Phone_User like", value, "phone_User");
			return (Criteria) this;
		}

		public Criteria andPhone_UserNotLike(String value) {
			addCriterion("Phone_User not like", value, "phone_User");
			return (Criteria) this;
		}

		public Criteria andPhone_UserIn(List<String> values) {
			addCriterion("Phone_User in", values, "phone_User");
			return (Criteria) this;
		}

		public Criteria andPhone_UserNotIn(List<String> values) {
			addCriterion("Phone_User not in", values, "phone_User");
			return (Criteria) this;
		}

		public Criteria andPhone_UserBetween(String value1, String value2) {
			addCriterion("Phone_User between", value1, value2, "phone_User");
			return (Criteria) this;
		}

		public Criteria andPhone_UserNotBetween(String value1, String value2) {
			addCriterion("Phone_User not between", value1, value2, "phone_User");
			return (Criteria) this;
		}

		public Criteria andMark_UserIsNull() {
			addCriterion("Mark_User is null");
			return (Criteria) this;
		}

		public Criteria andMark_UserIsNotNull() {
			addCriterion("Mark_User is not null");
			return (Criteria) this;
		}

		public Criteria andMark_UserEqualTo(Integer value) {
			addCriterion("Mark_User =", value, "mark_User");
			return (Criteria) this;
		}

		public Criteria andMark_UserNotEqualTo(Integer value) {
			addCriterion("Mark_User <>", value, "mark_User");
			return (Criteria) this;
		}

		public Criteria andMark_UserGreaterThan(Integer value) {
			addCriterion("Mark_User >", value, "mark_User");
			return (Criteria) this;
		}

		public Criteria andMark_UserGreaterThanOrEqualTo(Integer value) {
			addCriterion("Mark_User >=", value, "mark_User");
			return (Criteria) this;
		}

		public Criteria andMark_UserLessThan(Integer value) {
			addCriterion("Mark_User <", value, "mark_User");
			return (Criteria) this;
		}

		public Criteria andMark_UserLessThanOrEqualTo(Integer value) {
			addCriterion("Mark_User <=", value, "mark_User");
			return (Criteria) this;
		}

		public Criteria andMark_UserIn(List<Integer> values) {
			addCriterion("Mark_User in", values, "mark_User");
			return (Criteria) this;
		}

		public Criteria andMark_UserNotIn(List<Integer> values) {
			addCriterion("Mark_User not in", values, "mark_User");
			return (Criteria) this;
		}

		public Criteria andMark_UserBetween(Integer value1, Integer value2) {
			addCriterion("Mark_User between", value1, value2, "mark_User");
			return (Criteria) this;
		}

		public Criteria andMark_UserNotBetween(Integer value1, Integer value2) {
			addCriterion("Mark_User not between", value1, value2, "mark_User");
			return (Criteria) this;
		}

		public Criteria andEmail_UserIsNull() {
			addCriterion("Email_User is null");
			return (Criteria) this;
		}

		public Criteria andEmail_UserIsNotNull() {
			addCriterion("Email_User is not null");
			return (Criteria) this;
		}

		public Criteria andEmail_UserEqualTo(String value) {
			addCriterion("Email_User =", value, "email_User");
			return (Criteria) this;
		}

		public Criteria andEmail_UserNotEqualTo(String value) {
			addCriterion("Email_User <>", value, "email_User");
			return (Criteria) this;
		}

		public Criteria andEmail_UserGreaterThan(String value) {
			addCriterion("Email_User >", value, "email_User");
			return (Criteria) this;
		}

		public Criteria andEmail_UserGreaterThanOrEqualTo(String value) {
			addCriterion("Email_User >=", value, "email_User");
			return (Criteria) this;
		}

		public Criteria andEmail_UserLessThan(String value) {
			addCriterion("Email_User <", value, "email_User");
			return (Criteria) this;
		}

		public Criteria andEmail_UserLessThanOrEqualTo(String value) {
			addCriterion("Email_User <=", value, "email_User");
			return (Criteria) this;
		}

		public Criteria andEmail_UserLike(String value) {
			addCriterion("Email_User like", value, "email_User");
			return (Criteria) this;
		}

		public Criteria andEmail_UserNotLike(String value) {
			addCriterion("Email_User not like", value, "email_User");
			return (Criteria) this;
		}

		public Criteria andEmail_UserIn(List<String> values) {
			addCriterion("Email_User in", values, "email_User");
			return (Criteria) this;
		}

		public Criteria andEmail_UserNotIn(List<String> values) {
			addCriterion("Email_User not in", values, "email_User");
			return (Criteria) this;
		}

		public Criteria andEmail_UserBetween(String value1, String value2) {
			addCriterion("Email_User between", value1, value2, "email_User");
			return (Criteria) this;
		}

		public Criteria andEmail_UserNotBetween(String value1, String value2) {
			addCriterion("Email_User not between", value1, value2, "email_User");
			return (Criteria) this;
		}

		public Criteria andMemo_UserIsNull() {
			addCriterion("Memo_User is null");
			return (Criteria) this;
		}

		public Criteria andMemo_UserIsNotNull() {
			addCriterion("Memo_User is not null");
			return (Criteria) this;
		}

		public Criteria andMemo_UserEqualTo(String value) {
			addCriterion("Memo_User =", value, "memo_User");
			return (Criteria) this;
		}

		public Criteria andMemo_UserNotEqualTo(String value) {
			addCriterion("Memo_User <>", value, "memo_User");
			return (Criteria) this;
		}

		public Criteria andMemo_UserGreaterThan(String value) {
			addCriterion("Memo_User >", value, "memo_User");
			return (Criteria) this;
		}

		public Criteria andMemo_UserGreaterThanOrEqualTo(String value) {
			addCriterion("Memo_User >=", value, "memo_User");
			return (Criteria) this;
		}

		public Criteria andMemo_UserLessThan(String value) {
			addCriterion("Memo_User <", value, "memo_User");
			return (Criteria) this;
		}

		public Criteria andMemo_UserLessThanOrEqualTo(String value) {
			addCriterion("Memo_User <=", value, "memo_User");
			return (Criteria) this;
		}

		public Criteria andMemo_UserLike(String value) {
			addCriterion("Memo_User like", value, "memo_User");
			return (Criteria) this;
		}

		public Criteria andMemo_UserNotLike(String value) {
			addCriterion("Memo_User not like", value, "memo_User");
			return (Criteria) this;
		}

		public Criteria andMemo_UserIn(List<String> values) {
			addCriterion("Memo_User in", values, "memo_User");
			return (Criteria) this;
		}

		public Criteria andMemo_UserNotIn(List<String> values) {
			addCriterion("Memo_User not in", values, "memo_User");
			return (Criteria) this;
		}

		public Criteria andMemo_UserBetween(String value1, String value2) {
			addCriterion("Memo_User between", value1, value2, "memo_User");
			return (Criteria) this;
		}

		public Criteria andMemo_UserNotBetween(String value1, String value2) {
			addCriterion("Memo_User not between", value1, value2, "memo_User");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table User
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table User
     *
     * @mbg.generated do_not_delete_during_merge Tue Oct 09 08:53:29 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}