package org.iscas.tj2.pyt.springboot_mybatis.domain;

public class UserKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User.Id_User
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private Integer id_User;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User.WeixinId_User
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private String weixinId_User;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public UserKey(Integer id_User, String weixinId_User) {
		this.id_User = id_User;
		this.weixinId_User = weixinId_User;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public UserKey() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User.Id_User
	 * @return  the value of User.Id_User
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public Integer getId_User() {
		return id_User;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User.Id_User
	 * @param id_User  the value for User.Id_User
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setId_User(Integer id_User) {
		this.id_User = id_User;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User.WeixinId_User
	 * @return  the value of User.WeixinId_User
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public String getWeixinId_User() {
		return weixinId_User;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User.WeixinId_User
	 * @param weixinId_User  the value for User.WeixinId_User
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setWeixinId_User(String weixinId_User) {
		this.weixinId_User = weixinId_User == null ? null : weixinId_User.trim();
	}
}