package org.iscas.tj2.pyt.springboot_mybatis.domain;

public class UserMessageTemplet {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserMessageTemplet.Id_UserMessageTemplet
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	private Integer idUsermessagetemplet;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserMessageTemplet.Name_UserMessageTemplet
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	private String nameUsermessagetemplet;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserMessageTemplet.Type_UserMessageTemplet
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	private String typeUsermessagetemplet;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserMessageTemplet.Head_UserMessageTemplet
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	private String headUsermessagetemplet;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserMessageTemplet.Prefixion_UserMessageTemplet
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	private String prefixionUsermessagetemplet;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserMessageTemplet.Body_UserMessageTemplet
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	private String bodyUsermessagetemplet;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column UserMessageTemplet.Postfix_UserMessageTemplet
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	private String postfixUsermessagetemplet;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserMessageTemplet
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public UserMessageTemplet(Integer idUsermessagetemplet, String nameUsermessagetemplet,
			String typeUsermessagetemplet, String headUsermessagetemplet, String prefixionUsermessagetemplet,
			String bodyUsermessagetemplet, String postfixUsermessagetemplet) {
		this.idUsermessagetemplet = idUsermessagetemplet;
		this.nameUsermessagetemplet = nameUsermessagetemplet;
		this.typeUsermessagetemplet = typeUsermessagetemplet;
		this.headUsermessagetemplet = headUsermessagetemplet;
		this.prefixionUsermessagetemplet = prefixionUsermessagetemplet;
		this.bodyUsermessagetemplet = bodyUsermessagetemplet;
		this.postfixUsermessagetemplet = postfixUsermessagetemplet;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserMessageTemplet
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public UserMessageTemplet() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserMessageTemplet.Id_UserMessageTemplet
	 * @return  the value of UserMessageTemplet.Id_UserMessageTemplet
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public Integer getIdUsermessagetemplet() {
		return idUsermessagetemplet;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserMessageTemplet.Id_UserMessageTemplet
	 * @param idUsermessagetemplet  the value for UserMessageTemplet.Id_UserMessageTemplet
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public void setIdUsermessagetemplet(Integer idUsermessagetemplet) {
		this.idUsermessagetemplet = idUsermessagetemplet;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserMessageTemplet.Name_UserMessageTemplet
	 * @return  the value of UserMessageTemplet.Name_UserMessageTemplet
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public String getNameUsermessagetemplet() {
		return nameUsermessagetemplet;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserMessageTemplet.Name_UserMessageTemplet
	 * @param nameUsermessagetemplet  the value for UserMessageTemplet.Name_UserMessageTemplet
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public void setNameUsermessagetemplet(String nameUsermessagetemplet) {
		this.nameUsermessagetemplet = nameUsermessagetemplet == null ? null : nameUsermessagetemplet.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserMessageTemplet.Type_UserMessageTemplet
	 * @return  the value of UserMessageTemplet.Type_UserMessageTemplet
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public String getTypeUsermessagetemplet() {
		return typeUsermessagetemplet;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserMessageTemplet.Type_UserMessageTemplet
	 * @param typeUsermessagetemplet  the value for UserMessageTemplet.Type_UserMessageTemplet
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public void setTypeUsermessagetemplet(String typeUsermessagetemplet) {
		this.typeUsermessagetemplet = typeUsermessagetemplet == null ? null : typeUsermessagetemplet.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserMessageTemplet.Head_UserMessageTemplet
	 * @return  the value of UserMessageTemplet.Head_UserMessageTemplet
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public String getHeadUsermessagetemplet() {
		return headUsermessagetemplet;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserMessageTemplet.Head_UserMessageTemplet
	 * @param headUsermessagetemplet  the value for UserMessageTemplet.Head_UserMessageTemplet
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public void setHeadUsermessagetemplet(String headUsermessagetemplet) {
		this.headUsermessagetemplet = headUsermessagetemplet == null ? null : headUsermessagetemplet.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserMessageTemplet.Prefixion_UserMessageTemplet
	 * @return  the value of UserMessageTemplet.Prefixion_UserMessageTemplet
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public String getPrefixionUsermessagetemplet() {
		return prefixionUsermessagetemplet;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserMessageTemplet.Prefixion_UserMessageTemplet
	 * @param prefixionUsermessagetemplet  the value for UserMessageTemplet.Prefixion_UserMessageTemplet
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public void setPrefixionUsermessagetemplet(String prefixionUsermessagetemplet) {
		this.prefixionUsermessagetemplet = prefixionUsermessagetemplet == null ? null
				: prefixionUsermessagetemplet.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserMessageTemplet.Body_UserMessageTemplet
	 * @return  the value of UserMessageTemplet.Body_UserMessageTemplet
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public String getBodyUsermessagetemplet() {
		return bodyUsermessagetemplet;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserMessageTemplet.Body_UserMessageTemplet
	 * @param bodyUsermessagetemplet  the value for UserMessageTemplet.Body_UserMessageTemplet
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public void setBodyUsermessagetemplet(String bodyUsermessagetemplet) {
		this.bodyUsermessagetemplet = bodyUsermessagetemplet == null ? null : bodyUsermessagetemplet.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column UserMessageTemplet.Postfix_UserMessageTemplet
	 * @return  the value of UserMessageTemplet.Postfix_UserMessageTemplet
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public String getPostfixUsermessagetemplet() {
		return postfixUsermessagetemplet;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column UserMessageTemplet.Postfix_UserMessageTemplet
	 * @param postfixUsermessagetemplet  the value for UserMessageTemplet.Postfix_UserMessageTemplet
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	public void setPostfixUsermessagetemplet(String postfixUsermessagetemplet) {
		this.postfixUsermessagetemplet = postfixUsermessagetemplet == null ? null : postfixUsermessagetemplet.trim();
	}
}