package org.iscas.tj2.pyt.springboot_mybatis.domain;

public class Var {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Var.Id_Var
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private Integer idVar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Var.Id_Type
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private Integer idType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Var.Name_Var
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private String nameVar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Var.Changable_Var
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private String changableVar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Var.Memo_Var
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private String memoVar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Var.IfBreak_Var
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private Integer ifbreakVar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Var.SampleValue_Var
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private String samplevalueVar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Var.Id_NameSpace_Var
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private Integer idNamespaceVar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Var.IsSampleType_Var
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private Integer issampletypeVar;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Var
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public Var(Integer idVar, Integer idType, String nameVar, String changableVar, String memoVar, Integer ifbreakVar,
			String samplevalueVar, Integer idNamespaceVar, Integer issampletypeVar) {
		this.idVar = idVar;
		this.idType = idType;
		this.nameVar = nameVar;
		this.changableVar = changableVar;
		this.memoVar = memoVar;
		this.ifbreakVar = ifbreakVar;
		this.samplevalueVar = samplevalueVar;
		this.idNamespaceVar = idNamespaceVar;
		this.issampletypeVar = issampletypeVar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Var
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public Var() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Var.Id_Var
	 * @return  the value of Var.Id_Var
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public Integer getIdVar() {
		return idVar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Var.Id_Var
	 * @param idVar  the value for Var.Id_Var
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setIdVar(Integer idVar) {
		this.idVar = idVar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Var.Id_Type
	 * @return  the value of Var.Id_Type
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public Integer getIdType() {
		return idType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Var.Id_Type
	 * @param idType  the value for Var.Id_Type
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setIdType(Integer idType) {
		this.idType = idType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Var.Name_Var
	 * @return  the value of Var.Name_Var
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public String getNameVar() {
		return nameVar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Var.Name_Var
	 * @param nameVar  the value for Var.Name_Var
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setNameVar(String nameVar) {
		this.nameVar = nameVar == null ? null : nameVar.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Var.Changable_Var
	 * @return  the value of Var.Changable_Var
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public String getChangableVar() {
		return changableVar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Var.Changable_Var
	 * @param changableVar  the value for Var.Changable_Var
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setChangableVar(String changableVar) {
		this.changableVar = changableVar == null ? null : changableVar.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Var.Memo_Var
	 * @return  the value of Var.Memo_Var
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public String getMemoVar() {
		return memoVar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Var.Memo_Var
	 * @param memoVar  the value for Var.Memo_Var
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setMemoVar(String memoVar) {
		this.memoVar = memoVar == null ? null : memoVar.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Var.IfBreak_Var
	 * @return  the value of Var.IfBreak_Var
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public Integer getIfbreakVar() {
		return ifbreakVar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Var.IfBreak_Var
	 * @param ifbreakVar  the value for Var.IfBreak_Var
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setIfbreakVar(Integer ifbreakVar) {
		this.ifbreakVar = ifbreakVar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Var.SampleValue_Var
	 * @return  the value of Var.SampleValue_Var
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public String getSamplevalueVar() {
		return samplevalueVar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Var.SampleValue_Var
	 * @param samplevalueVar  the value for Var.SampleValue_Var
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setSamplevalueVar(String samplevalueVar) {
		this.samplevalueVar = samplevalueVar == null ? null : samplevalueVar.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Var.Id_NameSpace_Var
	 * @return  the value of Var.Id_NameSpace_Var
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public Integer getIdNamespaceVar() {
		return idNamespaceVar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Var.Id_NameSpace_Var
	 * @param idNamespaceVar  the value for Var.Id_NameSpace_Var
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setIdNamespaceVar(Integer idNamespaceVar) {
		this.idNamespaceVar = idNamespaceVar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Var.IsSampleType_Var
	 * @return  the value of Var.IsSampleType_Var
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public Integer getIssampletypeVar() {
		return issampletypeVar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Var.IsSampleType_Var
	 * @param issampletypeVar  the value for Var.IsSampleType_Var
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setIssampletypeVar(Integer issampletypeVar) {
		this.issampletypeVar = issampletypeVar;
	}
}