package org.iscas.tj2.pyt.springboot_mybatis.domain;

public class VarItem {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column VarItem.Id_VarItem
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private Integer idVaritem;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column VarItem.Id_Var
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private Integer idVar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column VarItem.NO_VarItem
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private Integer noVaritem;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column VarItem.SampleValue_VarItem
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private String samplevalueVaritem;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column VarItem.Memo_VarItem
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private String memoVaritem;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column VarItem.IsSampleType_VarItem
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	private Integer issampletypeVaritem;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table VarItem
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public VarItem(Integer idVaritem, Integer idVar, Integer noVaritem, String samplevalueVaritem, String memoVaritem,
			Integer issampletypeVaritem) {
		this.idVaritem = idVaritem;
		this.idVar = idVar;
		this.noVaritem = noVaritem;
		this.samplevalueVaritem = samplevalueVaritem;
		this.memoVaritem = memoVaritem;
		this.issampletypeVaritem = issampletypeVaritem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table VarItem
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public VarItem() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column VarItem.Id_VarItem
	 * @return  the value of VarItem.Id_VarItem
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public Integer getIdVaritem() {
		return idVaritem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column VarItem.Id_VarItem
	 * @param idVaritem  the value for VarItem.Id_VarItem
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setIdVaritem(Integer idVaritem) {
		this.idVaritem = idVaritem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column VarItem.Id_Var
	 * @return  the value of VarItem.Id_Var
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public Integer getIdVar() {
		return idVar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column VarItem.Id_Var
	 * @param idVar  the value for VarItem.Id_Var
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setIdVar(Integer idVar) {
		this.idVar = idVar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column VarItem.NO_VarItem
	 * @return  the value of VarItem.NO_VarItem
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public Integer getNoVaritem() {
		return noVaritem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column VarItem.NO_VarItem
	 * @param noVaritem  the value for VarItem.NO_VarItem
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setNoVaritem(Integer noVaritem) {
		this.noVaritem = noVaritem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column VarItem.SampleValue_VarItem
	 * @return  the value of VarItem.SampleValue_VarItem
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public String getSamplevalueVaritem() {
		return samplevalueVaritem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column VarItem.SampleValue_VarItem
	 * @param samplevalueVaritem  the value for VarItem.SampleValue_VarItem
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setSamplevalueVaritem(String samplevalueVaritem) {
		this.samplevalueVaritem = samplevalueVaritem == null ? null : samplevalueVaritem.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column VarItem.Memo_VarItem
	 * @return  the value of VarItem.Memo_VarItem
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public String getMemoVaritem() {
		return memoVaritem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column VarItem.Memo_VarItem
	 * @param memoVaritem  the value for VarItem.Memo_VarItem
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setMemoVaritem(String memoVaritem) {
		this.memoVaritem = memoVaritem == null ? null : memoVaritem.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column VarItem.IsSampleType_VarItem
	 * @return  the value of VarItem.IsSampleType_VarItem
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public Integer getIssampletypeVaritem() {
		return issampletypeVaritem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column VarItem.IsSampleType_VarItem
	 * @param issampletypeVaritem  the value for VarItem.IsSampleType_VarItem
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	public void setIssampletypeVaritem(Integer issampletypeVaritem) {
		this.issampletypeVaritem = issampletypeVaritem;
	}
}