package org.iscas.tj2.pyt.springboot_mybatis.dao;

import org.iscas.tj2.pyt.springboot_mybatis.domain.Function;

public interface FunctionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Function
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int deleteByPrimaryKey(Integer idFunction);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Function
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int insert(Function record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Function
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int insertSelective(Function record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Function
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	Function selectByPrimaryKey(Integer idFunction);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Function
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int updateByPrimaryKeySelective(Function record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Function
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int updateByPrimaryKey(Function record);
}