package org.iscas.tj2.pyt.springboot_mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.iscas.tj2.pyt.springboot_mybatis.domain.FuncVarItem;
import org.iscas.tj2.pyt.springboot_mybatis.domain.VarItem;

public interface FuncVarItemMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FuncVarItem
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int deleteByPrimaryKey(Integer idFuncvaritem);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FuncVarItem
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int insert(FuncVarItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FuncVarItem
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int insertSelective(FuncVarItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FuncVarItem
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	FuncVarItem selectByPrimaryKey(Integer idFuncvaritem);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FuncVarItem
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int updateByPrimaryKeySelective(FuncVarItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FuncVarItem
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int updateByPrimaryKey(FuncVarItem record);
	
	//2018-12-04 新增
	List<FuncVarItem> selectFuncVarItemsByFuncVarId(@Param("IdFuncVar") int intFuncVarId);
}