package org.iscas.tj2.pyt.springboot_mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.iscas.tj2.pyt.springboot_mybatis.domain.FuncVar;

public interface FuncVarMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int deleteByPrimaryKey(Integer idFuncvar);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int insert(FuncVar record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int insertSelective(FuncVar record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	FuncVar selectByPrimaryKey(Integer idFuncvar);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int updateByPrimaryKeySelective(FuncVar record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FuncVar
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int updateByPrimaryKey(FuncVar record);
	
	//2018-12-04 自己加的
	List<FuncVar> selectFuncVarsByFunctionId(@Param("IdFunction") int intFunctionId);
}