package org.iscas.tj2.pyt.springboot_mybatis.dao;

import org.iscas.tj2.pyt.springboot_mybatis.domain.FuncVarItem;

public interface FuncVarItemMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FuncVarItem
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int deleteByPrimaryKey(Integer idFuncvaritem);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FuncVarItem
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int insert(FuncVarItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FuncVarItem
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int insertSelective(FuncVarItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FuncVarItem
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	FuncVarItem selectByPrimaryKey(Integer idFuncvaritem);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FuncVarItem
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int updateByPrimaryKeySelective(FuncVarItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FuncVarItem
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int updateByPrimaryKey(FuncVarItem record);
}