package org.iscas.tj2.pyt.springboot_mybatis.dao;

import org.iscas.tj2.pyt.springboot_mybatis.domain.NameSpace;

public interface NameSpaceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table NameSpace
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	int deleteByPrimaryKey(Integer idNamespace);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table NameSpace
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	int insert(NameSpace record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table NameSpace
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	int insertSelective(NameSpace record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table NameSpace
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	NameSpace selectByPrimaryKey(Integer idNamespace);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table NameSpace
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	int updateByPrimaryKeySelective(NameSpace record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table NameSpace
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	int updateByPrimaryKey(NameSpace record);
}