package org.iscas.tj2.pyt.springboot_mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.iscas.tj2.pyt.springboot_mybatis.domain.Permission;

public interface PermissionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Permission
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int deleteByPrimaryKey(Integer idPermission);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Permission
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int insert(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Permission
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int insertSelective(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Permission
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	Permission selectByPrimaryKey(Integer idPermission);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Permission
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int updateByPrimaryKeySelective(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Permission
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int updateByPrimaryKey(Permission record);
	
	//2018-12-07
	List<Permission> selectByGivenProjectAndRight(@Param("IdProject") int IdProject, @Param("IdRight") int IdRight);
}