package org.iscas.tj2.pyt.springboot_mybatis.dao;

import org.iscas.tj2.pyt.springboot_mybatis.domain.Permission;

public interface PermissionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Permission
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int deleteByPrimaryKey(Integer idPermission);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Permission
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int insert(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Permission
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int insertSelective(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Permission
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	Permission selectByPrimaryKey(Integer idPermission);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Permission
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int updateByPrimaryKeySelective(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Permission
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int updateByPrimaryKey(Permission record);
}