package org.iscas.tj2.pyt.springboot_mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.iscas.tj2.pyt.springboot_mybatis.domain.Project;
import org.iscas.tj2.pyt.springboot_mybatis.domain.Struct;

public interface StructMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Struct
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	int deleteByPrimaryKey(Integer idStruct);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Struct
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	int insert(Struct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Struct
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	int insertSelective(Struct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Struct
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	Struct selectByPrimaryKey(Integer idStruct);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Struct
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	int updateByPrimaryKeySelective(Struct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Struct
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	int updateByPrimaryKey(Struct record);

	//2018-11-20 新增
	 List<Struct> selectStructsByUserId(@Param("IdUser") int intUserId);
}