package org.iscas.tj2.pyt.springboot_mybatis.dao;

import org.iscas.tj2.pyt.springboot_mybatis.domain.StructItem;

public interface StructItemMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table StructItem
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int deleteByPrimaryKey(Integer idStructitem);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table StructItem
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int insert(StructItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table StructItem
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int insertSelective(StructItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table StructItem
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	StructItem selectByPrimaryKey(Integer idStructitem);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table StructItem
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int updateByPrimaryKeySelective(StructItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table StructItem
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int updateByPrimaryKey(StructItem record);
}