package org.iscas.tj2.pyt.springboot_mybatis.dao;

import org.iscas.tj2.pyt.springboot_mybatis.domain.StructUserRelation;

public interface StructUserRelationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table StructUserRelation
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	int deleteByPrimaryKey(Integer idStructuserrelation);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table StructUserRelation
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	int insert(StructUserRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table StructUserRelation
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	int insertSelective(StructUserRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table StructUserRelation
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	StructUserRelation selectByPrimaryKey(Integer idStructuserrelation);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table StructUserRelation
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	int updateByPrimaryKeySelective(StructUserRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table StructUserRelation
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	int updateByPrimaryKey(StructUserRelation record);
}