package org.iscas.tj2.pyt.springboot_mybatis.dao;

import org.iscas.tj2.pyt.springboot_mybatis.domain.Struct;

public interface StructMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Struct
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int deleteByPrimaryKey(Integer idStruct);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Struct
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int insert(Struct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Struct
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int insertSelective(Struct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Struct
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	Struct selectByPrimaryKey(Integer idStruct);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Struct
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int updateByPrimaryKeySelective(Struct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Struct
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int updateByPrimaryKey(Struct record);
}