package org.iscas.tj2.pyt.springboot_mybatis.dao;

import org.iscas.tj2.pyt.springboot_mybatis.domain.TypeUserRelation;

public interface TypeUserRelationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TypeUserRelation
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int deleteByPrimaryKey(Integer idTypeuserrelation);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TypeUserRelation
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int insert(TypeUserRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TypeUserRelation
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int insertSelective(TypeUserRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TypeUserRelation
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	TypeUserRelation selectByPrimaryKey(Integer idTypeuserrelation);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TypeUserRelation
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int updateByPrimaryKeySelective(TypeUserRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TypeUserRelation
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int updateByPrimaryKey(TypeUserRelation record);
}