package org.iscas.tj2.pyt.springboot_mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.iscas.tj2.pyt.springboot_mybatis.domain.Struct;
import org.iscas.tj2.pyt.springboot_mybatis.domain.Type;

public interface TypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Type
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int deleteByPrimaryKey(Integer idType);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Type
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int insert(Type record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Type
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int insertSelective(Type record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Type
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	Type selectByPrimaryKey(Integer idType);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Type
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int updateByPrimaryKeySelective(Type record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Type
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int updateByPrimaryKey(Type record);
	
	//2018-11-20 新增
	List<Type> selectTypesByUserId(@Param("IdUser") int intUserId);
}