package org.iscas.tj2.pyt.springboot_mybatis.dao;

import org.iscas.tj2.pyt.springboot_mybatis.domain.Type;

public interface TypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Type
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int deleteByPrimaryKey(Integer idType);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Type
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int insert(Type record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Type
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int insertSelective(Type record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Type
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	Type selectByPrimaryKey(Integer idType);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Type
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int updateByPrimaryKeySelective(Type record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Type
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int updateByPrimaryKey(Type record);
}