package org.iscas.tj2.pyt.springboot_mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.iscas.tj2.pyt.springboot_mybatis.domain.User;
import org.iscas.tj2.pyt.springboot_mybatis.domain.UserExample;
import org.iscas.tj2.pyt.springboot_mybatis.domain.UserKey;

public interface UserMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	long countByExample(UserExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	int deleteByExample(UserExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	int deleteByPrimaryKey(UserKey key);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	int insert(User record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	int insertSelective(User record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	List<User> selectByExample(UserExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	User selectByPrimaryKey(UserKey key);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	int updateByExample(@Param("record") User record, @Param("example") UserExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	int updateByPrimaryKeySelective(User record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table User
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	int updateByPrimaryKey(User record);
	/*
     * 自己加的insert，依赖于xml
     */
    int Myinsert(User user);
	/*
     * 自己加的insert，采用@Insert注解，不依赖于xml
     */
    @Insert("INSERT INTO User(Id_User,WeixinId_User,Account_User,Name_User) VALUES(#{id_User},#{weixinId_User}, #{account_User}, #{name_User})")
    int MyinsertNoXml(User user);
    
    /*
     * 自己加的select，根据微信id取用户情况
     */
    @Select("SELECT User.* FROM User WHERE WeixinId_User = #{weixinId}")
	User selectUserByWeixinId(@Param("weixinId") String strWeixinId);
}