package org.iscas.tj2.pyt.springboot_mybatis.dao;

import org.iscas.tj2.pyt.springboot_mybatis.domain.UserRoleRelation;

public interface UserRoleRelationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserRoleRelation
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int deleteByPrimaryKey(Integer idUserrolerelation);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserRoleRelation
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int insert(UserRoleRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserRoleRelation
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int insertSelective(UserRoleRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserRoleRelation
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	UserRoleRelation selectByPrimaryKey(Integer idUserrolerelation);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserRoleRelation
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int updateByPrimaryKeySelective(UserRoleRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table UserRoleRelation
	 * @mbg.generated  Fri Oct 12 09:57:46 CST 2018
	 */
	int updateByPrimaryKey(UserRoleRelation record);
}