package org.iscas.tj2.pyt.springboot_mybatis.dao;

import org.iscas.tj2.pyt.springboot_mybatis.domain.Var;

public interface VarMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Var
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	int deleteByPrimaryKey(Integer idVar);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Var
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	int insert(Var record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Var
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	int insertSelective(Var record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Var
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	Var selectByPrimaryKey(Integer idVar);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Var
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	int updateByPrimaryKeySelective(Var record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Var
	 * @mbg.generated  Sun Dec 02 10:35:33 CST 2018
	 */
	int updateByPrimaryKey(Var record);
}