package org.iscas.tj2.pyt.springboot_mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.iscas.tj2.pyt.springboot_mybatis.domain.Var;

public interface VarMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Var
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int deleteByPrimaryKey(Integer idVar);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Var
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int insert(Var record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Var
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int insertSelective(Var record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Var
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	Var selectByPrimaryKey(Integer idVar);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Var
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int updateByPrimaryKeySelective(Var record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table Var
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int updateByPrimaryKey(Var record);
	
	//2018-12-03 自己加的
	List<Var> selectVarsByProjectId(@Param("IdProject") int intProjectId);		

}