package org.iscas.tj2.pyt.springboot_mybatis.dao;

import org.iscas.tj2.pyt.springboot_mybatis.domain.VarProjectRelation;

public interface VarProjectRelationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table VarProjectRelation
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int deleteByPrimaryKey(Integer idVarprojectrelation);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table VarProjectRelation
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int insert(VarProjectRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table VarProjectRelation
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int insertSelective(VarProjectRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table VarProjectRelation
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	VarProjectRelation selectByPrimaryKey(Integer idVarprojectrelation);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table VarProjectRelation
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int updateByPrimaryKeySelective(VarProjectRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table VarProjectRelation
	 * @mbg.generated  Mon Dec 03 18:53:01 CST 2018
	 */
	int updateByPrimaryKey(VarProjectRelation record);
}